Fix `triangular_solve` meta function out parameter names.
This PR replaces the parameter names specified in the `triangular_solve_meta`
function (specifically in its `out_wrapper(...)` decorator) by those written in the
_native_functions.yaml_ file.

This name mismatch caused the operation to fail when using the meta device (see error
below):

```python
Traceback (most recent call last):
  File "examples/test.py", line 23, in <module>
    torch.triangular_solve(b.to("meta"), A.to("meta"), out=meta_out)
  File "torch/_decomp/__init__.py", line 100, in _fn
    return f(*args, **kwargs, out=None if is_none else out_kwargs)
  File "torch/_prims_common/wrappers.py", line 289, in _fn
    result = fn(*args, **kwargs)
TypeError: triangular_solve_meta() got an unexpected keyword argument 'X'
```

ghstack-source-id: 65a873d944f57a99a645a10fccf81ccdff6c67d5
Pull Request resolved: https://github.com/pytorch/pytorch/pull/140186